#+title: Dot files and scripts used on Linux
#+AUTHOR: tomrut
#+OPTIONS: toc:3
#+OPTIONS: p:t

#+TOC: headlines 3

* Scripts
** Multimedia files conversion
** Playing music - command line
I use mpg123 to play my mp3 music files for years. Recently I've found fzf (fuzzy find) tool and I've got an idea to use it to accelerate search and kick of playing songs from my music gallery.

Below you will find three handy scripts I've created for quick finding and playing of music:

*** FZF + mocp [[[file:bin/p]]]
It uses MOCP to play the songs from selected directory and its subdirectories. It also plays flac files if you install flac decoder.

#+begin_src

#!/bin/bash
# depends on: fzf and mocp (music on console)

musicDir=~/Music
fzfSelectedDir="$(find $musicDir -type d|fzf)"
mocp -m "$fzfSelectedDir" -c -a "$fzfSelectedDir" -p
mocp
#+end_src
*** FZF + mpg123 + playlist creation [[[file:bin/m1]]]
It creates a playlist, saves it in selected directory and uses mpg123 to play it.
#+begin_src shell

#!/bin/bash
# depends on: fzf and mpg123 - create a list.m3u file in selected folder then passes it to play to mpg123

musicDir=~/Music
fzfSelectedDir="$(find $musicDir -type d|fzf)"
cd "$fzfSelectedDir"
find ./ -iregex '.*.mp.*' -type f -print > list.m3u
mpg123 --list list.m3u
#+end_src
*** FZF + mpg123 [[[file:bin/m2]]]
It plays songs from selected directory passing songs list directly to mpg123. You need to use ctrl+c to go to next track.
#+begin_src shell

#!/bin/bash
# depends on: fzf and mpg123 - need to do ctrl+c to go to next track

musicDir=~/Music
fzfSelectedDir="$(find $musicDir -type d|fzf)"
cd "$fzfSelectedDir"
find ./ -iname '*.mp3' -type f -print | mpg123 --list -

#+end_src

* Emacs
** Doom emacs configuration [[[file:.doom.d]]]
* Other
