#+title: Dot files and scripts used on Linux
#+AUTHOR: tomrut
#+OPTIONS: toc:3
#+OPTIONS: p:t


* Scripts
** Playing youtube using ~yt-dlp~ + ~mpv~ player.
This script is supposed to be run from active youtube tab in ~firefox~ browser. It can be adjusted for chrome by changing ~--class~ parameter. The best is to attach it as shortcut in your Window Manager.
#+begin_src shell

#!/bin/bash
window_id=$(xdotool search --onlyvisible --class "firefox")
xdotool key --window $window_id --delay 20 --clearmodifiers ctrl+l ctrl+c Escape

yt-dlp -o -  $(xclip -o)|mpv -

#+end_src
** Playing music - command line
I use mpg123 to play my mp3 music files for years. Recently I've found fzf (fuzzy find) tool and I've got an idea to use it to accelerate search and kick of playing songs from my music gallery.

Below you will find three handy scripts I've created for quick finding and playing of music:

*** [[HTTPS://github.com/junegunn/fzf][FZF]] + [[https://moc.daper.net][mocp]] [[file:bin/p]]
It uses _mocp_ to play the songs from selected directory and its subdirectories. Its advantage over mpg123 is that it can also play flac files if you have installed /flac/ decoder.
#+begin_src shell

#!/bin/bash
# depends on: fzf and mocp (music on console)

musicDir=~/Music
fzfSelectedDir="$(find $musicDir -type d|fzf)"
mocp -m "$fzfSelectedDir" -c -a "$fzfSelectedDir" -p
mocp
#+end_src
*** [[HTTPS://github.com/junegunn/fzf][FZF]] + mpg123 + playlist creation [[file:bin/m1]]
It creates a playlist, saves it in selected directory and uses mpg123 to play it.
#+begin_src shell

#!/bin/bash
# depends on: fzf and mpg123 - create a list.m3u file in selected folder then passes it to play to mpg123

musicDir=~/Music
fzfSelectedDir="$(find $musicDir -type d|fzf)"
cd "$fzfSelectedDir"
find ./ -iregex '.*.mp.*' -type f -print > list.m3u
mpg123 --list list.m3u
#+end_src
*** [[HTTPS://github.com/junegunn/fzf][FZF]] + mpg123 [[file:bin/m2]]
It plays songs from selected directory passing songs list directly to mpg123. You need to use ctrl+c to go to next track.
#+begin_src shell
#!/bin/bash
# depends on: fzf and mpg123 - need to do ctrl+c to go to next track

musicDir=~/Music
fzfSelectedDir="$(find $musicDir -type d|fzf)"
cd "$fzfSelectedDir"
find ./ -iname '*.mp3' -type f -print | mpg123 --list -

#+end_src
** Multimedia files conversion
*** mp4 to mp3
**** [[file:bin/mp4intomp3.sh][mp4intomp3]] - it uses ~avconv~ for doing conversion
**** [[file:bin/mp42mp3.sh][mp42mp3.sh]] - it uses ~ffmpeg~
**** [[file:bin/mp4tomp3.sh][mp4tomp3]] - it uses ~fmpeg~ and ~lame~
*** 3gp to mp3
**** [[file:bin/3gp2mp3.sh][3gp2mp3.sh]] - it uses ~avconv~ converter
* Neovim
** [[file:.config/nvim][.config/nvim]] neovim configuration
* Emacs
** Doom Emacs configuration [[[file:.doom.d]]]
* Other
** Javascript example
#+begin_src js
const sum = (a, b) => {
    return a + b;
}

console.log('simple calculation:' + sum(30, 82))
#+end_src
